config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "events#index"
  filter :locale,    :exclude => /^\/root/


  resources :events do
    resources :schedules do
      collection do
        get :search
      end
    end
  end

  #schddules自己的routes
  resources :schedules do
    collection do
      get :get_spot_phtot
      get :search_spot
      post :add_to_wish
      delete :destroy_wish

    end
  end

  resources :details do
    #resources :spots
  end

  resources :wishes, only: :show


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :schedule
  belongs_to :spot
  #model validation
  validates_presence_of :hr, :category_id
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :events_of_users, dependent: :destroy
  
  has_many :favorites, dependent: :destroy

  has_many :likes, dependent: :destroy

  has_many :replies, dependent: :destroy

  has_many :schedules, dependent: :destroy
end

app/models/events_of_user.rb
class EventsOfUser < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :event
  has_many :details, dependent: :destroy

end

app/models/spot.rb
class Spot < ApplicationRecord
  has_many :details ,dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :replies, dependent: :destroy

  has_many :likes, dependent: :destroy

  has_many :favorites, -> { order(created_at: :desc) }, dependent: :destroy

  has_many :events_of_users, -> { order(created_at: :desc) },dependent: :destroy
end

app/models/wish.rb
class Wish < ApplicationRecord
  has_many :wish_items, dependent: :destroy


   def add_wish_item(place_id,url)
    existing_item = wish_items.find_by( place_id: place_id )
    if existing_item
      #已經加入待選清單
      return false
    else
      #@client = GooglePlaces::Client.new(GoogleKey,:language => I18n.locale)
      #spot = @client.spot(place_id)
      @client = GooglePlaces::Client.new(GoogleKey)
      spot = @client.spot(place_id, detail: true,language: I18n.locale)
      #新增到spot??
      Spot.where(place_id: place_id).first_or_create do |newspot|
        #newspot = spot,
        newspot.image = url
        newspot.place_id = place_id
        newspot.address = spot.formatted_address
        newspot.rating = spot.rating
        newspot.lat = spot.lat
        newspot.lng = spot.lng
        newspot.spot_name = spot.name

    end

      wish_item = wish_items.build( district: spot.region, lat:spot.lat, lng:spot.lng, place_id: place_id, spot_name: spot.name,image: url,address: spot.formatted_address,rating: spot.rating )
      wish_item.save!
      self.wish_items
      return true
    end
  end


end

app/models/wish_item.rb
class WishItem < ApplicationRecord
  belongs_to :wish
  #geocoded_by :address        #從address欄位取出地址
  
  #after_validation :geocode   #將取出的地址自動轉為經緯度分別存在 latitude、longitude 欄位
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale
  helper_method :current_wish
  #設定expore time
  helper_method :check_expires

  def set_locale
    if params[:locale] && I18n.available_locales.include?( params[:locale].to_sym )
    session[:locale] = params[:locale]
    end

    I18n.locale = session[:locale] || I18n.default_locale
  end

  private
  def current_wish
    @wish || set_wish # return @wish if @wish exist, or call set_wish
  end

  def set_wish

    if session[:wish_id]
      @wish = Wish.find_by(id: session[:wish_id])
    end

    @wish ||= Wish.create

    session[:wish_id] = @wish.id
    session[:expires_at] = Time.current + 2.hours
    @wish
  end

  #判斷待選清單的expire time,超過時間就刪除
  def check_expires
    if session[:expires_at] < Time.current
      #destroy wish
      @wish = Wish.find_by(id: session[:wish_id])
      @wish.destroy
    end

  end

end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  #before_action :set_detail, only: [:show, :edit, :update, :destroy]

  def new
    #用get,所以可以傳schedule_id,place_id
    #找出spot
    @detail = Detail.new
    #@WishItem = params[:place_id]
    @spot = Spot.where(place_id: params[:place_id]).first
    #@spot = Spot.where(place_id:"ChIJqZwyeygCaDQRgqs_sMMtcvo").first
    #@spot = Spot.last
    #要有如果找不到的防呆
    @schedules = Schedule.find(params[:schedule_id])
    #test data
    #@event = Event.find(3)
    #@schedules = @event.schedules.last
    #render :new
    #回傳的view不要含有layout
    render :layout => false
  end

 def create
    #1.找出該筆spot_id - 用place去找
    #begin
    @schedules = Schedule.find(params[:detail][:schedule_id])

    #要有如果找不到的防呆!!!!!!
    @spot = Spot.find(params[:detail][:spot_id])
    #rescue ActiveRecord::RecordNotFound
    #    @msgResult =  "error"


    params[:detail].parse_time_select! :start_t
    @detail = @spot.details.build(detail_params)
    #@detail.start_t = start_t

    @detail.schedule = @schedules


    if @detail.save
      @msgResult = "detail was scuccessfully created"
     else
      @msgResult = "detail was failed to create"
     end

    #render :json => { :msgResult => @msgResult }
  end

  def show

  end

  private



  def set_detail
    @detail = Detail.find(params[:id])
  end

  def detail_params
    params.require(:detail).permit(:hr, :category_id, :content, :traffic,:start_t,:spot_id,:schedule_id)

  end



end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  #排定行程method
  def new
    @wishLists = current_wish.wish_items.all
    #for 測試
    @event = Event.find(3)

    @schedules = @event.schedules.all
    #@schedules = @event.schedules.all
  end

  def show
    @schedule = Schedule.find(params[:id])
    @Category = Category.all
    render :layout => false
  end

  #搜尋行程default
  #根據前面輸入的國家和地點自動帶入(先寫死)
  def search
    @client = GooglePlaces::Client.new(GoogleKey)
    @spots= @client.spots_by_query('大阪機場',{ language: I18n.locale})
    @categories = Category.all
  end


  def search_spot
    @client = GooglePlaces::Client.new(GoogleKey)

    #category = Category.first
     category = Category.find_by(id:params[:category])
    
    if category.nil?
      #@category = Category.find(params[:category])
      destination = params[:destination]
    else
       destination = params[:destination] + category.name
    end

    spots = @client.spots_by_query( destination,:language => I18n.locale)
    render :json => { :spots => spots }
  end

  #取照片要另外呼叫方法
  def get_spot_phtot
    @client = GooglePlaces::Client.new(GoogleKey)
    @spot = @client.spot(params[:place_id], {detail: true,language: 'zh'})
    url =  @spot.photos[0].fetch_url(800)
    render :json => { :url => url, :resultSpot => @spot}
  end

  def add_to_wish
    @place_id = params[:placeId]
    @url = params[:url]

    #這裡寫法會再調整
    if !current_wish.add_wish_item(@place_id,@url)
      render :json => { :errors => "這個景點已在待選清單"},:status => 405
    else
      render :json => { :wishTems => current_wish.wish_items.last }
    end
  end

  def destroy_wish
    puts params[:id]
    @wish_item = WishItem.find(params[:id])
    @wish_item.destroy
    render :json => { :id => @wish_item.id }
  end


end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  def show
    @wish = Wish.find(params[:id])
    render :layout => false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/details/_form.html.erb
<% if @detail.errors.any? %>
  <h2>We have some erroes here !</h2>
  <ul>
    <% @detail.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>

<% end %>

<div class="container">
  <div class="form-group">
    <%= form_for @detail,{ remote: true } do |f| %>
    <form>
      <table>
        <tr class="form-group">
          <td>
            category
          </td>
          <td>
            <%= f.collection_select :category_id , Category.all, :id,:name,{prompt:true},{class: "form-control",:required => true} %>
          </td>
        </tr>

        <tr class="form-group">
          <td>
            <%= f.label 'days'%>
          </td>
          <td>
            <%= f.label @schedules.day %>
            <%= f.hidden_field :schedule_id ,:value => @schedules.id %>
            <%= f.hidden_field :spot_id, :value => @spot.id %>
          </td>
        </tr>

        <tr>
          <td>
            spot_name
          </td>
          <td>
            <%= @spot.spot_name%>
          </td>
        </tr>

        <tr>
          <td>
            Photo
          </td>
          <td>
            <%= image_tag @spot.image,width:'300px' if @spot.image?%>
          </td>
        </tr>

        <tr>
          <td>
            start_t
          </td>
          <td>
            <%= f.time_select :start_t,
            :combined => true,
           # :default => Time.now.change(:hour => 08, :min => 00),
            :minute_interval => 30,
            :time_separator => "",
            :ampm => true


%>
          </td>
        </tr>

        <tr>
          <td>
            Hours
          </td>
          <td>
            <%= f.select :hr, options_for_select(1..24), { prompt: "hours" },{:required => true }%>
          </td>
        </tr>

        <tr>
          <td>
            <%= f.label :traffic, "traffic tool"%>
          </td>
          <td>
            <%= f.text_field :traffic %>
          </td>
        </tr>

        <tr>
          <td>
            <%= f.label :content, "content"%>
          </td>
          <td>
            <%= f.text_area :content, placeholder: "140 character...", maxlength: 140,rows: 5, class:"form-control",id:"message" %>
          </td>
        </tr>

      </table>

      <%= f.submit "新增" ,class:"btn btn-primary btn-right" %>
    </form>
  <% end %>
</div>

</div>

app/views/details/create.js.erb
/*
var detail = document.createElement("center");
detail.id = "detail-<%= @detail.id %>";
$(detail).html($("#spot-add-template").html());
$(detail).find(".conteaner").html('<%= @detail.spot.spot_name %>');
$("#<%= @schedules.id %>").append(detail);
*/


 function reload(scheduleId){
      $.ajax({
        url: "/schedules/" + scheduleId,
        method: "GET",
        dataType: "HTML",

        error: function (xhr) {
          $('#newpage').html("ERROR");
          
        },
        success: function (data) {

          //$("schedule-"+id).find('.schedule-content').html(data);
          $("#schedule-content-" + scheduleId).html(data);
          $('#newpage').html('<%=@msgResult%>');
        }
      });
    }
    reload(<%=@schedules.id%>);

app/views/details/new.html.erb
<%= render :partial =>"form" %>

app/views/details/show.html.erb
<div>success</div>

app/views/schedules/_items.html.erb
<% details.each do |detail| %>
  <center id="detail-<%= detail.id %>">
    <div class="conteaner">
      <div><%=detail.start_t%></div>
      <h3><%=detail.spot.spot_name%></h3>
      <div><%=detail.category_id%></div>
      <div><%=detail.hr%></div>
      <div><%=detail.content%></div>
    </div>
  </center>
<%end%>

app/views/schedules/search.html.erb
<div class="container">
  <!--search box-->
  <div class="place-input">
    <div class="col-md-4">
      <div id="custom-search-input">
        <div class="input-group col-md-12">
          <input id="content" type="text" class="form-control input-lg" placeholder="Search"/>
          <span class="input-group-btn" onclick="searchFromStr()">
            <%= octicon "search" ,:height => 24, :class => "right left" %>
          </span>
        </div>
      </div>
      <div class="search-type">
        <%#=collection_select(:search, :category_id, Category.all, :id, :name, prompt: true, {class: "form-control"} ,required: true)%>
          <%#= (collection_select :category_id, Category.all, :id, :name, {prompt: true}, {class: "form-control"}) %>
            <%= select_tag 'category', options_for_select([["請選擇" , "0" ]] +@categories.collect{ |u| [u.name, u.id] })%>
          </div>
          <br>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8">
          <div class="map-bolck">
            <p class="map-note"><%=t("schedule.search.which are you prefer? making your wish")%></p>
            <div id="map"><%=t("schedule.map_content")%></div>
          </div>

        </div>
        <div class="col-md-4">
          <!--wish list-->
          <div class="choses-item">
            <h2><%=t("schedule.wish")%></h2>
            <div class="place-item">
              <table class="my-table table table-hover">

                <tbody id="places">
                  <% current_wish.wish_items.order(:district).each do |item| %>
                    <tr id="<%= item.id %>">
                      <td class="item-list"><%= item.spot_name%></td>
                      <td>
                        <i class="far fa-trash-alt delete-wishspot"></i>
                      </td>
                    </tr>

                  <%end%>
                </tbody>
              </table>
            </div>
          </div>
          <div class="manage-list">
            <button type="button" class="btn btn-primary"><%=t("schedule.search.start_planning")%></button>

            <%= link_to t("schedule.search.start_planning"), new_event_schedule_path,method: :get, class: "btn btn-primary"%>
          </div>
        </div>
      </div>

      <!-- Modal -->
      <div class="modal fade" id="spot-detail-info" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div id="model-body" class="modal-body">
              <!--spot info-->

              <div id="spot-show">
                <a id="spot-map-url" href="" target="_blank" class="main-title">
                  <i class='fas fa-globe'></i>
                </a>
                <h5 id="spot-name"></h5>
                <h6 id="spot-address"></h6>
                <div id="spot-rsting"></div>
                <a href=""><img id="spot-pic"></a>

                <br>

              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="addSpotTowish()"><%=t("schedule.search.add")%></button>
            </div>
          </div>
        </div>
      </div>

    </div>

    <script>
      var currentInfoWindow = null;

      function initialize(spots) {
        var location = {
          lat: 44.5403,
          lng: -78.5463
        }

        if (spots.length > 0) {
          location = {
            lat: spots[0].lat,
            lng: spots[0].lng
          }
        }
        //new map init
        var map = new google.maps.Map(document.getElementById('map'), {
          center: location,
          zoom: 12
        });

        var marker;
        //get each spot details
        spots.forEach(function (spot) {

          // if(spot.rating > 4){
          marker = new google.maps.Marker({
            position: {
              lat: spot.lat,
              lng: spot.lng
            },
            map: map
          });

          //customized infowindow content
          attachSecretMessage(
            marker,
            "<h6>" + spot.name + "</h6><div id ='rating'>" + spot.rating + "</div><a id='web-link' target='_blank' href=''><i class='fas fa-home'></i><a/><button onclick='addSpotTowish()' class='btn btn-light btn-sm'><i class='far fa-plus-square'></i></button><" +
                "button type='button' data-toggle='modal' data-target='#spot-detail-info' class='btn btn-light btn-sm'><i class='fas fa-info-circle'></i></button><br><img id='small-pic'><div hidden id='place'>" + spot.place_id + "</div>",
            spot.place_id,
            map
          )
          // }
        })

      }

      function attachSecretMessage(marker, secretMessage, placeId, map) {
        //console.log(placeId);
        var infowindow;

        marker.addListener('click', function () {
          if (currentInfoWindow != null) {
            currentInfoWindow.close();
          }
          map.setZoom(14);
          map.setCenter(marker.getPosition());
          infowindow = new google.maps.InfoWindow({
            content: "<div class='map_price' id='spot-info'>" + secretMessage + "<br></div>"
          });

          //照片需要另外call方法
          getPhoto(placeId);

          infowindow.open(marker.get('map'), marker);
          currentInfoWindow = infowindow;
        });

      }

      function getPhoto(placeId) {

        var url;
        var resultSpot;
        $("#review-info").remove();

        $.ajax({
          url: "/schedules/get_spot_phtot?place_id=" + placeId,
          method: "GET",
          dataType: "json",
          success: function (data) {
            url = data["url"];
            resultSpot = data["resultSpot"];
            var smallSpot = document.getElementById("small-pic");
            smallSpot.setAttribute("src", url);

            $("#web-link").attr("href", resultSpot.website);
            //for open window
            var spot = document.getElementById("spot-pic");
            spot.setAttribute("src", url);

            var spotWeb = document.getElementById("spot-map-url");
            spotWeb.setAttribute("href", resultSpot.url);

            $("#spot-name").html(resultSpot.name);

            $("#spot-rsting").html("<i class='far fa-star'></i>" + resultSpot.rating);
            $("#spot-address").html(resultSpot.formatted_address);

            //creat new comment info
            var info = document.createElement("div");
            info.id = "review-info";
            $("#spot-show").append(info);
            console.log(resultSpot.reviews.length);
            for (var i = 0; i < resultSpot.reviews.length; i++) {
              var review = document.createElement("div");
              review.id = "spot-reviews";
              $(review).html($("#review-template").html());
              $(review).find(".review-text").html('<%= octicon "comment" %>' + resultSpot.reviews[i].text);
              $(review).find(".review-rating").html("<br>評價: " + resultSpot.reviews[i].rating);
              $(review).find(".review-name").html("<i class='far fa-user-circle'></i>" + resultSpot.reviews[i].author_name);

              $("#review-info").append(review);
            }
          }
        });

      }

      //搜尋
      function searchFromStr() {
        var str = document.getElementById("content");
        var category = $("#category").val()
        //console.log(str.value);
        $.ajax({
          //url: "/schedules/search_spot?destination=" + str.value + "&category"+category,
          url: "/schedules/search_spot",
          method: "GET",
          dataType: "json",
          data: {
            destination: $("#content").val(),
            category: $("#category").val()
          },
          success: function (data) {
            initialize(data["spots"]);
          }
        });

      }
      //待選清單
      function addSpotTowish() {
        $.ajax({
          url: "/schedules/add_to_wish",
          method: "POST",
          dataType: "json",
          data: {
            placeId: $("#place").html(),
            url: $("#spot-pic").attr('src')
          },
          error: function (xhr) {
            var errMessage = $.parseJSON(xhr.responseText).errors
            alert(errMessage);
          },
          success: function (data) {
            //目前可以存地區,但要做到頁面續有點太複雜（先改到下一步顯示地區
            /*
var region = document.createElement("tr");
          region.id = "district";
          //  var point = $("#district").find(".item-list");
           // if(!$("#district").find(".item-list").innerHTML == data["wishTems"].district) {
            /*
            var region = document.createElement("tr");
            region.id = data["wishTems"].id;
              $(region).html($("#spot-title-template").html());
              $(region).find(".item-list").html(data["wishTems"].district);
              $("#place-title").append(region);
            //}
*/

            var spot = document.createElement("tr");
            spot.id = data["wishTems"].id;
            $(spot).html($("#spot-template").html());
            $(spot).find(".item-list").html(data["wishTems"].spot_name);
            $("#places").append(spot);
            /*
            var message = document.createElement("div");
            message.id ="result";

            $("#result").html("success")
            $("#spot-show").replaceWith($("#result"));*/
            alert("success");

          }
        });

      }

      //delete spot
      $("#places").on("click", ".delete-wishspot", function (event) {
        var id = event.target.parentNode.parentNode.id;
        //console.log(id);

        $.ajax({
          url: "/schedules/destroy_wish",
          method: "DELETE",
          dataType: "json",
          data: {
            id: id
          },
          success: function (data) {
            $("#" + data["id"]).remove();
            setTimeout("alert('已成功刪除')", 200);
          }
        });

      });

      $(function () {
        // always pass csrf tokens on ajax calls
        $.ajaxSetup({
          headers: {
            'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
          }
        });
      });
      //default onload
      google.maps.event.addDomListener(window, 'load', function () {
        initialize(<%= raw @spots.to_json %>)
      });

      //關閉視窗前呼叫
      /*
$("#spot-detail-info").on("hide.bs.modal",function(e){
  console.log('關閉視窗前呼叫');
    $("#review-info").remove();

});*/
    </script>
    <!-- <script type="text/template" id="spot-title-template"> <td class="item-list"></td> <td></td> </script> -->
    <script type="text/template" id="spot-template">
      <td class="item-list"></td>
      <td>
        <i class="far fa-trash-alt delete-wishspot"></i>
      </td>
    </script>

    <script type="text/template" id="review-template">

      <div class="review-text"></div>
      <div class="review-rating"></div>
      <h6 class="review-name"></h6>
      <hr>

    </script>

app/views/schedules/show.html.erb
<% @schedule.details.all.each do |detail| %>

    <!--map link 
    <button type="button" class="btn btn-primary">
      <i class="fas fa-globe"></i>
    </button>-->
    <% category = Category.find(detail.category_id)%>
    <div id="detail-<%= detail.id %>">
     
        <h5><%= detail.spot.spot_name%></h5>
        <div><%=detail.start_t.strftime("at %I:%M%p") %></div>
        <div>Category : <%=category.name%></div>
        <div>stay time : <%=detail.hr%> hr</div>
        <div>notes : <%=detail.content%></div>
      </div>
  
    </div>
 <hr>
<% end %>

app/views/wishes/show.html.erb
<h3>Wish List</h3>
<table class="my-table table table-hover">
    <% region = nil %>
        <% @wish.wish_items.all.order(:district).each do |item| %>
            <% if item.district != region %>
                <thead id="wish-title" class="thead-light">
                    <tr id="wishItem-<%= item.id %>">
                        <td class="item-list">
                            <%=item.district%>
                        </td>
                    </tr>
                    <% region = item.district %>
                </thead>
                <%end%>
                    <tbody id="wish-list">
                        <tr id="wishItem-<%= item.id %>">
                            <td class="item-list">
                                <%=item.spot_name%>
                            </td>
                        </tr>
                        <%end%>
                </tbody>
</table>